### ISSUE TITLE
Related research

### ISSUE THREAD

**Issue by leoj3n** [bitovi/eslint-config-bitovi#7]
Initially we weren't sure if something better than ESLint existed, and did some research:

https://github.com/donejs/developer-relations/issues/22

Never really sparked a discussion, but in my opinion ESLint is the best option for us.

**Comment by christopherjbaker** [comment]
I remember this coming up, but not sure where. I think it came down to the purpose of ESLint vs Prettier. The purpose of the latter being to fix the code, while the purpose of the former to identify problems and leave most fixing to the user.

**Comment by imjoshdean** [comment]
Prettier seems fine, but it is less active than eslint is and with a less robust ability to develop for it.

ESLint it is. 🙌
