### ISSUE TITLE
Root ruleset

### ISSUE THREAD

**Issue by christopherjbaker** [bitovi/eslint-config-bitovi#9]
I'm not sure the best place to add the note, but I would suggest that the rules files in the projects contain the `"root": true` option. This prevents any eslint configs in parent directories from influencing the project. The cascading is useful when you want new rules in a directory (such as extra globals for your tests), but can cause issues when a developer has a file at a higher level that is interacting with the lower level project file.

**Comment by imjoshdean** [comment]
Is there a situation we should run into where this config wouldn't be placed in the parent directory of a project?

**Comment by christopherjbaker** [comment]
Its more when there is another one higher up. IE:

```
Projects/
  .eslintrc // all my projects will use this, with a global `eslint
  Bitovi/
    can-stache/
      .eslintrc // project specific
```

The linting inside can-stache will get rules from Projects/.eslint and from Projects/Bitovi/can-stache/.eslint (the closer files taking precedence). If you put `"root": true` inside can-stache/.eslint, it will not look higher up.
